### ISSUE TITLE
No module named denso_control.controllers

### ISSUE THREAD

**Issue by aip1996** [hungpham2511/rapid-transport#2]
Hi,When I ran the executable 'pick-demo', I encountered the following error:

No module named denso_control.controllers
INFO 00:46:00,627 (transport.console.pick_and_place) [__init__: 227] Only run in OpenRAVE.
CRITICAL 00:46:02,208 (transport.console.pick_and_place) [__init__: 258] Object object2 is in collision.
......
Traceback (most recent call last):
  File "/home/aip/.local/bin/transport.paper", line 11, in <module>
    load_entry_point('toppra-object-transport', 'console_scripts', 'transport.paper')()
  File "/home/aip/git/rapid-transport/transport/console/console_main.py", line 85, in main
    execute=args.execute, slowdown=args.slowdown, mode=args.mode)
  File "/home/aip/git/rapid-transport/transport/console/pick_and_place.py", line 30, in main
    success = demo.run()
  File "/home/aip/git/rapid-transport/transport/console/pick_and_place.py", line 547, in run
    amult=0.999)
  File "/home/aip/.local/lib/python2.7/site-packages/toppra-0.2-py2.7-linux-x86_64.egg/toppra/planning_utils.py", line 94, in retime_active_joints_kinematics
    gridpoints=gridpoints, solver_wrapper=solver_wrapper)
  File "/home/aip/.local/lib/python2.7/site-packages/toppra-0.2-py2.7-linux-x86_64.egg/toppra/algorithm/reachabilitybased/reachability_algorithm.py", line 76, in __init__
    self.solver_wrapper = seidelWrapper(self.constraints, self.path, self.gridpoints)
  File "toppra/solverwrapper/cy_seidel_solverwrapper.pyx", line 421, in toppra.solverwrapper.cy_seidel_solverwrapper.seidelWrapper.__init__
TypeError: compute_constraint_params() takes exactly 4 arguments (3 given)

I am looking forward to your help to solve this problem. Thank you very much

**Comment by hungpham2511** [comment]
Hi @aip1996, this looks like a version incompatibility issue. 

Could you try to check out commit: 79a9b7df8996c88e56888c0ce861bd7935e929da (toppra) and try running the example again?

Please let me know if it works for you.
